AIwithQos/DynamicQoS/DynamicQoS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('QoSGui.urls')),
    path('api/v1/', include('QoSAPI.urls','APIv1')),
    path('manager/', include('QoSmanager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

AIwithQos/DynamicQoS/QoSAPI/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import *

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'applications', ApplicationViewSet, basename='application')
router.register(r'devices', DeviceViewSet, basename='devices')
router.register(r'tuning', TuningViewSet, basename='tuning')

urlpatterns = [
    path('add-device', AddDevice.as_view(), name="add-device"),
    path('add-topology', AddTopology.as_view(), name="add-topology"),
    path('topology', TopologyByName.as_view(), name="topology-by-name"),
    path('preapare-env', preapare_environment.as_view(), name="preapare-environment"),
    path('discover-network', discover_network.as_view(), name="discover-network"),
    path('configure-monitoring', configure_monitoring.as_view(), name="configure-monitoring"),
    path('start-monitoring', start_monitoring.as_view(), name="start-monitoring"),
    path('topologiesbrief', ListTopologiesBrief.as_view(), name="topologies"),
    path('devicesbrief', ListDevicesBrief.as_view(), name="devices"),
    path('interfacesbrief', ListInterfacesBrief.as_view(), name="interfaces"),
    path('flowtable', FlowTable.as_view(), name="flowtable"),
    path('flowtabletworates', FlowTableTwoRates.as_view(), name="flowtabletworates"),
    path('current-flows', FlowsInterface.as_view(), name="currentflows"),
    path('flow-charts', FlowCharts.as_view(), name="flow-charts"),
    path('', include(router.urls)),

]
app_name = 'APIv1'

AIwithQos/DynamicQoS/QoSmanager/models.py
from datetime import date, datetime

import napalm
from DynamicQoS.settings import MEDIA_ROOT
from django.db import models
# Create your models here.
from jinja2 import Environment, FileSystemLoader
from napalm import get_network_driver
from netaddr import *
from netmiko import ConnectHandler
from .validator import *


class Topology(models.Model):
    topology_name = models.CharField(max_length=255)
    topology_desc = models.CharField(max_length=255)

    def __str__(self):
        return self.topology_name


class BusinessType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class BusinessApp(models.Model):
    name = models.CharField(max_length=255)
    business_type = models.ForeignKey(BusinessType, on_delete=models.CASCADE, null=True)
    match = models.CharField(max_length=255)
    recommended_dscp = models.CharField(max_length=255)
    delay_ref = models.IntegerField()
    loss_ref = models.IntegerField()

    @property
    def priority(self):
        if self.recommended_dscp.startswith("a"):
            return self.recommended_dscp[2]

    @property
    def drop(self):
        if self.recommended_dscp.startswith("a"):
            return self.recommended_dscp[3]

    @property
    def __str__(self):
        return self.name


class Policy(models.Model):
    name = models.CharField(max_length=255, unique=True, error_messages={'unique': 'this name is in used'})
    description = models.CharField(max_length=255)
    enable = models.BooleanField(default=False)
    deploy = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class PolicyIn(models.Model):
    policy_ref = models.ForeignKey(Policy, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    @property
    def name(self):
        return self.policy_ref.name

    @property
    def description(self):
        return self.policy_ref.description

    @property
    def render_policy(self):
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        classes = Application.objects.filter(policy_in_id=self.id)
        named = env.get_template("policyIn.j2")
        config_file = named.render(classes=classes, a=self)
        config = config_file.splitlines()
        return config_file

    @property
    def render_no_policy(self):
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        classes = Application.objects.filter(policy_in_id=self.id)
        named = env.get_template("no_policyIn.j2")
        config_file = named.render(classes=classes, a=self)
        config = config_file.splitlines()
        # driver = napalm.get_network_driver('ios')
        # device = driver(hostname='192.168.5.1', username='admin',
        #                 password='admin')
        #
        # print('Opening ...')
        # device.open()
        # print('Loading replacement candidate ...')
        # device.load_merge_candidate(config=config_file)
        # print('\nDiff:')
        # print(device.compare_config())
        # print('Committing ...')

        return config_file

    @property
    def remove_applications(self):
        apps = Application.objects.filter(policy_in=self)
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        output = env.get_template("remove_applications.j2")
        config_file = output.render(applications=apps)
        return config_file

    @property
    def add_applications(self):
        apps = Application.objects.filter(policy_in=self)
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        output = env.get_template("add_applications.j2")
        config_file = output.render(applications=apps)
        return config_file


class PolicyOut(models.Model):
    policy_ref = models.ForeignKey(Policy, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    @property
    def name(self):
        # interface = Interface.objects.get(policy_out_ref=self)
        interfaces = Interface.objects.all()
        for i in interfaces:
            if i.policy_out_ref == self:
                return "OUT_{}_{}".format(self.policy_ref.name, i.interface_name)

    @property
    def description(self):
        return self.policy_ref.description

    @property
    def render_policy(self):
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        groups = Group.objects.filter(policy=self.policy_ref)
        regroupement_classes = RegroupementClass.objects.filter(policy_out_id=self.id)
        dscp_list = Dscp.objects.all()
        classes = Application.objects.all()
        named = env.get_template("policyOut.j2")
        config_file = named.render(groups=groups, classes=classes, a=self, regroupement_classes=regroupement_classes,
                                   dscp_list=dscp_list)
        return config_file

    @property
    def render_no_policy(self):
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        groups = Group.objects.filter(policy=self.policy_ref)
        named = env.get_template("no_policyOut.j2")
        config_file = named.render(groups=groups, a=self)
        return config_file

    @property
    def service_policy(self):
        interface = Interface.objects.get(policy_out_ref=self)
        env = Environment(loader=FileSystemLoader(str(MEDIA_ROOT[0]) + "/monitoring_conf/"))
        output = env.get_template("service_policy.j2")
        config_file = output.render(interface=interface)
        return config_file


class Policing(models.Model):
    cir = models.CharField(max_length=255)
    pir = models.CharField(max_length=255)
    dscp_transmit = models.CharField(max_length=255)


class Shaping(models.Model):
    peak = models.CharField(max_length=255)
    average = models.CharField(max_length=255)


class Group(models.Model):
    name = models.CharField(max_length=255)
    policy = models.ForeignKey(Policy, on_delete=models.CASCADE, null=True)
    priority = models.CharField(max_length=255)

    @property
    def all_applications(self):
        return len(Application.objects.filter(group=self))

    @property
    def list_applications(self):
        return Application.objects.filter(group=self)


class RegroupementClass(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    policing = models.ForeignKey(Policing, on_delete=models.CASCADE, null=True)
    shaping = models.ForeignKey(Shaping, on_delete=models.CASCADE, null=True)
    policy_out = models.ForeignKey(PolicyOut, on_delete=models.CASCADE, null=True)
    bandwidth = models.CharField(max_length=255)
    priority = models.CharField(max_length=255)
    bits = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    @property
    def name(self):
        return self.group.name

    @property
    def oppressed_tos(self):
        oppressed = None
        v = 0
        dscps = Dscp.objects.filter(regroupement_class=self)
        for tos in dscps:
            if tos.delay_ratio >= 2 or tos.loss_ratio >= 2:
                if tos.c_ratio > v:
                    v = tos.c_ratio
                    oppressed = tos

        return oppressed

    @property
    def excessive_tos(self):
        excessive = None
        v = 0
        dscps = Dscp.objects.filter(regroupement_class=self)
        for tos in dscps:
            if tos.ratio >= v:
                v = tos.ratio
                excessive = tos

        return excessive


class Dscp(models.Model):
    dscp_value = models.CharField(max_length=255)
    regroupement_class = models.ForeignKey(RegroupementClass, on_delete=models.CASCADE, null=True)
    drop_min = models.CharField(max_length=255)
    drop_max = models.CharField(max_length=255)
    denominator = models.CharField(max_length=255)
    drop_min_old = models.CharField(max_length=255)
    drop_max_old = models.CharField(max_length=255)
    drop_min_new = models.CharField(max_length=255)
    drop_max_new = models.CharField(max_length=255)
    delay = models.IntegerField(null=True, default=400)
    loss = models.IntegerField(null=True, default=20)
    ratio = models.IntegerField(null=True, default=40)

    @property
    def delay_ref(self):
        apps = Application.objects.filter(mark=self.dscp_value)
        delays = []
        for app in apps:
            delays.append(app.business_app.delay_ref)
        if len(delays) == 0:
            return self.delay
        else:
            return min(delays)

    @property
    def loss_ref(self):
        apps = Application.objects.filter(mark=self.dscp_value)
        delays = []
        for app in apps:
            delays.append(app.business_app.loss_ref)
        if len(delays) == 0:
            return self.loss
        else:
            return min(delays)

    @property
    def delay_ratio(self):
        return round(self.delay / self.delay_ref)

    @property
    def loss_ratio(self):
        return round(self.loss / self.loss_ref)

    @property
    def c_ratio(self):
        if self.dscp_value != "EF":
            c = int(self.dscp_value[3])
            return c * max(self.delay_ratio, self.loss_ratio)
        else:
            return 0


class Application(models.Model):
    RECOMMENDED, CS6, EF, CS5, AF43, AF42, AF41, CS4, AF33, \
    AF32, AF31, CS3, AF23, AF22, AF21, CS2, AF13, AF12, \
    AF11, CS1, DEFAULT = "RECOMMENDED", "CS6", "EF", "CS5", "AF43", "AF42", "AF41", "CS4", "AF33", \
                         "AF32", "AF31", "CS3", "AF23", "AF22", "AF21", "CS2", "AF13", "AF12", "AF11", "CS1", "DEFAULT"
    DSCP = (
        (RECOMMENDED, "RECOMMENDED"),
        (CS6, "CS6"),
        (EF, "EF"),
        (CS5, "CS5"),
        (AF43, "AF43"),
        (AF42, "AF42"),
        (AF41, "AF41"),
        (CS4, "CS4"),
        (AF33, "AF33"),

AIwithQos/DynamicQoS/templates/ChartsPage.html
{% extends "base2.html" %}
{% load staticfiles %}
{% block content %}
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
                <h3 class="kt-portlet__head-title">
                    Monitoring Charts
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                    </div>
                </div>
            </div>
        </div>

        <div class="kt-portlet__body">
            <div class="container">

                <div class="row">
                    <div class="card" style="width: 120%">
                        <div class="card-header">
                            <p class="text-center">Application</p>
                            <ul class="nav nav-tabs card-header-tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#app_bandwith" data-toggle="tab">Bandwith</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#app_delay" data-toggle="tab">Delay</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#app_jitter" data-toggle="tab">Jitter</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#app_packet" data-toggle="tab">Packet loss</a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="tab-pane" id="app_bandwith">
                                    <button id="renderBtn">
                                        Render
                                    </button>
                                    <div class="container">
                                        <div id="loadingMessage"></div>
                                        <canvas id="myChart"></canvas>
                                    </div>
                                </div>
                                <div class="tab-pane" id="app_delay">Delay</div>
                                <div class="tab-pane" id="app_jitter">Jitter</div>
                                <div class="tab-pane" id="app_packet">Packet loss</div>
                            </div>
                        </div>
                    </div>
                </div>

                <br> <br>

                <div class="row">
                    <div class="card" style="width: 120%">
                        <div class="card-header">
                            <p class="text-center">ToS</p>
                            <ul class="nav nav-tabs card-header-tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#tos_bandwith" data-toggle="tab">Bandwith</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#tos_delay" data-toggle="tab">Delay</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#tos_jitter" data-toggle="tab">Jitter</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#tos_packet" data-toggle="tab">Packet loss</a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="tab-pane" id="tos_bandwith">Bandwith</div>
                                <div class="tab-pane" id="tos_delay">Delay</div>
                                <div class="tab-pane" id="tos_jitter">Jitter</div>
                                <div class="tab-pane" id="tos_packet">Packet loss</div>
                            </div>
                        </div>
                    </div>
                </div>

                <br> <br>

                <div class="row">
                    <div class="card" style="width: 120%">
                        <div class="card-header">
                            <p class="text-center">Flow</p>
                            <ul class="nav nav-tabs card-header-tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#bandwith" data-toggle="tab">Bandwith</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#flow_delay" data-toggle="tab">Delay</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#flow_jitter" data-toggle="tab">Jitter</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#flow_packet" data-toggle="tab">Packet loss</a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="tab-pane" id="flow_bandwith">Bandwith</div>
                                <div class="tab-pane" id="flow_delay">Delay</div>
                                <div class="tab-pane" id="flow_jitter">Jitter</div>
                                <div class="tab-pane" id="flow_packet">Packet loss</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        function renderChart(data, labels) {
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: labels,
                    datasets: [
                        {
                            label: 'Firefox',
                            data: data[0],
                            borderColor: 'rgba(75, 192, 192, 1)',
                            backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        },
                        {
                            label: 'Windows',
                            data: data[1],
                            borderColor: 'rgba(192, 192, 192, 1)',
                            backgroundColor: 'rgba(192, 192, 192, 0.2)',
                        },
                        {
                            label: 'Chrome',
                            data: data[2],
                            borderColor: 'rgba(60, 200, 40, 1)',
                            backgroundColor: 'rgba(60, 200, 40, 0.2)',
                        }
                    ]
                },
                options: {
                    hover: {
                        mode: 'index'

                    },
                    tooltips: {
                        mode: 'index',
                    },
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                callback: function (value, index, values) {
                                    return float2dollar(value);
                                }
                            }
                        }]
                    },
                }
            });
        }

        function getChartData() {
            $("#loadingMessage").html('<img src="./giphy.gif" alt="" srcset="">');
            $.ajax({
                url: "https://api.myjson.com/bins/1awwc1",
                success: function (result) {
                    $("#loadingMessage").html("");
                    var data = [];
                    data.push(result.Firefox);
                    data.push(result.Windows);
                    data.push(result.Chrome);
                    var labels = result.labels;
                    renderChart(data, labels);
                },
                error: function (err) {
                    $("#loadingMessage").html("Error");
                }
            });
        }

        $("#renderBtn").click(
            function () {
                getChartData();
            }
        );

        function float2dollar(value) {
            return value;
        }


    </script>

{% endblock %}

AIwithQos/DynamicQoS/templates/application_dropdown_list_options.html
<option value="">------------</option>
{% for business_app in business_apps %}
<option value="{{ business_app.pk }}">{{ business_app.name }}</option>
{% endfor %}

AIwithQos/DynamicQoS/templates/devices.html
{% extends 'base2.html'%}
{% block content%}

{% load staticfiles %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Applications Details</a>
        </li>
    </ol>

    <div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
              <i class="fa fa-plus"></i> Custom Application
            </div>
            <div class="card-body">
                  <form method="post" id="custom_form" action="{% url 'add_custom_application' police_id %}">
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">business_type :</label>
                            {{ custom_form.custom_name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputLastName">business_app:</label>
                            {{ custom_form.protocol_type}}
                        </div>
                    </div>
                       <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputLastName">business_app:</label>
                            {{ custom_form.port_number}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">app_priority:</label>
                            {{ custom_form.app_priority}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">drop_prob:</label>
                            {{ custom_form.drop_prob}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">begin_time :</label>
                            {{ custom_form.begin_time}}
                        </div>
                    </div>
                      <div class="form-group">
                    <div class="col-md-8">
                        <label for="exampleInputName"> end_time:</label>
                        {{ custom_form.end_time}}
                    </div>
                    </div>
                      <div class="form-group">
                    <div class="col-md-8">
                        <label for="exampleInputName">source :</label>
                        {{ custom_form.source}}
                    </div>
                    </div>
                      <div class="form-group">
                    <div class="col-md-8">
                        <label for="exampleInputName">destination :</label>
                        {{ custom_form.destination}}
                    </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <button type="submit" class="btn btn-primary btn-block" >Add</button>
                        </div>
                    </div>
                  </form>
            </div>
        </div>
    </div>


    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
              <i class="fa fa-plus"></i> New Application
            </div>
            <div class="card-body">
                  <form method="post" id="app_form" action="{% url 'add_application' police_id %}" data-application-url="{% url 'ajax_load_applications' %}" novalidate >
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">business_type :</label>
                            {{ app_form.business_type}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputLastName">business_app:</label>
                            {{ app_form.business_app}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">app_priority:</label>
                            {{ app_form.app_priority}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">drop_prob:</label>
                            {{ app_form.drop_prob}}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <label for="exampleInputName">begin_time :</label>
                            {{ app_form.begin_time}}
                        </div>
                    </div>
                      <div class="form-group">
                    <div class="col-md-8">
                        <label for="exampleInputName"> end_time:</label>
                        {{ app_form.end_time}}
                    </div>
                    </div>
                      <div class="form-group">
                    <div class="col-md-8">
                        <label for="exampleInputName">source :</label>
                        {{ app_form.source}}
                    </div>
                    </div>
                      <div class="form-group">
                    <div class="col-md-8">
                        <label for="exampleInputName">destination :</label>
                        {{ app_form.destination}}
                    </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8">
                            <button type="submit" class="btn btn-primary btn-block" >Add</button>
                        </div>
                    </div>
                  </form>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
              <i class="fa fa-folder-open"></i> Recent Applications
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for app in apps %}
                    <li class="list-group-item">
                            <div>
                                <i class="fa fa-th-list">
                                </i> <h5 style="display: inline-block">{{ app.name }}</h5>

                                <span class="pull-right">
                                     <a class="mr-3 d-inline-block pull-right" data-id="{{ app.id }}" href="#" ><i class="fa fa-trash" data-toggle="modal" ></i></a>


                                    <a class="mr-3 d-inline-block pull-right" href="#" ><i class="fa fa-stream"></i></a>
                                </span>
                            </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <a  class="card-footer clearfix small z-1" href="#">
              <span class="float-left">View all</span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
        </div>
    </div>

    </div>


  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_business_type").change(function () {
      var url = $("#app_form").attr("data-application-url");
      var business_type_id = $(this).val();

      $.ajax({
        url: url,
        data: {
          'business_type': business_type_id
        },
        success: function (data) {
          $("#id_business_app").html(data);
        }
      });

    });
  </script>


{%endblock%}